import type { ChronicleEntry } from "../chronicle-types";

const entry: ChronicleEntry = {
  "slug": "from-consumer-to-producer",
  "title": "From Consumer to Producer",
  "date": "September 30, 2026",
  "sortDate": "2026-09-30",
  "storyYear": 2014,
  "storyPeriod": "2014 to 2016",
  "tag": "Origins / Events",
  "readTime": "3 min read",
  "excerpt": "I went to my first festival at 23 expecting a big party. Two years later, I was wondering who built the stage. Soon after, I was organizing my first party-bus trip.",
  "featuredSummary": "I went to my first festival at 23 expecting a big party. Two years later, I was wondering who built the stage. Soon after, I was organizing my first party-bus trip.",
  "image": "/chronicles-from-consumer-to-producer.jpg",
  "imageAlt": "Illustration of a festival stage and crowd with road cases and coiled cables in the foreground at sunset",
  "sections": [
    {
      "paragraphs": [
        "The first time I walked into Sunset Music Festival, I was 23 years old and had no idea what I was walking into.",
        "My friend Zach had invited me. I was getting into electronic music through Pandora stations, Borgore, things like that. But I’d never been to a festival.",
        "I expected a big party.",
        "Instead, I walked in and felt like every one of my senses had been turned all the way up.",
        "The stages. The lights. The bass. The crowds. The scale of everything happening around us.",
        "Zach and I just walked around blown away.",
        "I remember Benny Benassi. I remember being in utter amazement.",
        "And I remember immediately wanting more.",
        "That was Sunset Music Festival in Tampa in 2014.",
        "Later that year, Zach and I drove from Fort Myers to EDC Orlando with two friends. That trip did something else: it introduced me to Orlando.",
        "After the festival, we could walk around the city. There were people everywhere. Things were happening. Compared with Fort Myers, Orlando felt bigger and full of possibility.",
        "Within a few months, I moved there.",
        "I transferred restaurants, eventually landed at Rainforest Cafe, and kept going to events.",
        "By TomorrowWorld 2015, something else was starting to happen. I wasn’t only attending anymore. When I found friends camping elsewhere, I convinced them to move over with us. I helped coordinate people and figure out how our campsite should be laid out.",
        "I didn’t think of that as event operations.",
        "I was just the guy trying to make everything work.",
        "Then I went to EDC New York in May 2016.",
        "At some point, I found myself standing there looking at a stage and thinking about how it had gotten there.",
        "Someone designed it.",
        "Someone manufactured it.",
        "Someone shipped it.",
        "Someone built it.",
        "Thousands of people had entered the festival smoothly. The bars worked. The bathrooms weren’t a nightmare. Problems I’d seen at other events simply weren’t problems here.",
        "I stopped looking only at what was happening onstage and started noticing the machine around it.",
        "I remember thinking:",
        "I want to be a producer instead of a consumer.",
        "About a month later, I went to Tampa Beach Bar for the first time.",
        "Brillz and Excision were playing. The place was beautiful. There was sand in front of the stage, an incredible sunset behind everything, a hotel attached to the venue, and after midnight the party moved inside.",
        "There was just one problem.",
        "It was a pain in the ass getting there from Orlando.",
        "A few hours into the show, I had an idea.",
        "I was feeling particularly inspired.",
        "What if I brought everyone here on a bus?",
        "So I started bouncing around the venue asking friends and acquaintances:",
        "Would you take a party bus from Orlando to this?",
        "The response was overwhelmingly yes.",
        "That was enough for me.",
        "I went home and started Googling buses. I emailed the venue until I got connected with their promotion manager. I started negotiating transportation and ticket prices.",
        "Less than a week later, on June 26, 2016, I ran my first Orlando Party Bus to Tampa Beach Bar for Adventure Club.",
        "About a dozen people got on that first bus.",
        "I lost money.",
        "I ran another one anyway.",
        "People wanted what I was offering. I just hadn’t figured out how to make the numbers work.",
        "They had a great time. They didn’t have to make the long drive. They could drink without worrying about driving home. They traveled with friends, got a deal on admission, and the transportation became part of the event itself.",
        "I planned to run the entire summer series.",
        "At the time, I wasn’t thinking about building an event company or creating a career. I wanted to cover my expenses, put on something good, and have fun doing it.",
        "Looking back, though, I can see the transition happening.",
        "In 2014, I walked into Sunset completely overwhelmed by something other people had created.",
        "In May 2016, I stood at EDC New York wondering how people created something that large.",
        "A month later, I was walking around Tampa Beach Bar asking people if they’d get on a bus with me.",
        "I had stopped asking where the next party was.",
        "I was starting to figure out how to build one."
      ]
    }
  ]
};

export default entry;
